### ISSUE TITLE
Request: tutorial

### ISSUE THREAD

**Issue by omarcostahamido** [jwoehr/qisjob#11]
I would like to request a tutorial on how to best use current qis_job.
In particular I would like to understand what is the best workflow to figure out the least busy machines, and how to list just the queue size for each machine.

**Comment by jwoehr** [comment]
- By default qisjob chooses least busy.
- Queue depth is `--status` ... see the `pending_jobs` value
```$ qisjob --backend ibmqx2 --status
{   'backend_name': 'ibmqx2',
    'backend_version': '2.2.5',
    'operational': True,
    'pending_jobs': 907,
    'status_msg': 'active'}
````

**Comment by jwoehr** [comment]
Does this require anything else?

**Comment by omarcostahamido** [comment]
no. thank you very much for this.
I'd be glad to add myself a tutorial on qisjob for Max in the future.
