### ISSUE TITLE
don't quit python please! 🛑 

### ISSUE THREAD

**Issue by omarcostahamido** [jwoehr/qisjob#17]
beside the using it in the terminal, I am now exploring using qisjob in a python script.
(long story short, I'm trying to find ways to cut on the time spend just loading python, see more on #16 )
It seems that once the `do_it()` method gets called on any QisJob object, it will quit the python.
For the laymen (such as me self), it's all the `sys.exit(some number?)` on the `qis_job.pyx` that need not to be run.

OCH

**Comment by omarcostahamido** [comment]
For the record: I think qisjob works as intended in the terminal, so please don't break it. Now, if it is possible to know when we are in the python script world, and change the behavior there, then yes, that will make sense to change it, and will be helpful.

**Comment by jwoehr** [comment]
I opened an `issue_17` branch and checked in some code that will work better. It will still exit on certain errors, like a job failure. Totally removing `sys.exit()` will take more control flow work and I can't do that tonite.

**Comment by jwoehr** [comment]
This is a good change. It really should only exit when running as a script. The object itself should never call `sys.exit()`. Thanks for bringing this to my attention. QisJob is two years old soon and has gone through much evolution :)

**Comment by jwoehr** [comment]
Been looking at how to straighten this all out.
I have to document better each method in the `QisJob` class.
Then I have to redo some code that's been sitting there for two years.
So the "real" fix is not a one-day thing. It's going to be a fairly major change in QisJob.

**Comment by omarcostahamido** [comment]
No problem. I don't think it is that urgent, I can live with the 1300ms
delay right now.
I will be able to focus on improving this more probably after the PhD 0:-)

**Comment by jwoehr** [comment]
Closed by b1cea140cd318a65808fcdd786c63096c284d226

**Comment by omarcostahamido** [comment]
thank you. it is a-working now!
