### ISSUE TITLE
correct change date

### ISSUE THREAD

**Issue by omarcostahamido** [jwoehr/qisjob#19]
you used binary to say the month of change here:
https://github.com/jwoehr/qisjob/commit/36b978db3b5f56dd0e6404db46c1c3e3357f830a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R95
change it back to `02`?

**Comment by jwoehr** [comment]
Ha! oops. Fixing that, thanks!
