### ISSUE TITLE
qis_job and qisjob

### ISSUE THREAD

**Issue by omarcostahamido** [jwoehr/qisjob#3]
the repo is called qis_job but the command is qisjob.
would it be a good idea to make this consistent and rename the repo to qisjob?

**Comment by jwoehr** [comment]
Probably a good idea.

**Comment by jwoehr** [comment]
ISTR that if you change the name of a repo the old name still points to it? Not sure how GitHub works on that.

**Comment by omarcostahamido** [comment]
Oh yes, I've also seen that happening on repos that I've changed the name.
I reckon it is a nice feature to have.

**Comment by jwoehr** [comment]
If we do this it will make sense to change the module name as well.
That's a lot of work.
We're going to think about this for a while.

**Comment by jwoehr** [comment]
9e0f433 closes

**Comment by omarcostahamido** [comment]
🎉
