### ISSUE TITLE
supressing warnings?

### ISSUE THREAD

**Issue by omarcostahamido** [jwoehr/qisjob#6]
everytime I `qisjob -h` I get at the top:
```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: UserWarning: QuantumInspire not installed.
  return f(*args, **kwds)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: UserWarning: Rigetti Forest not installed.
  return f(*args, **kwds)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: UserWarning: qiskit-jku-provider not installed.
  return f(*args, **kwds)
(...)
```

would it be possible to suppress it here and only show the warning if I attempt to use any of those backends without the required prerequisite?

**Comment by omarcostahamido** [comment]
these are quite annoying, anything I do they print to the console.

**Comment by jwoehr** [comment]
Yes, I should do that. I got coerced into putting `imports` at head of file by `pylint`. They used to be in the branches where the code is called :)

**Comment by jwoehr** [comment]
Added -w flag

**Comment by omarcostahamido** [comment]
feel free to close this issue when you feel good about these changes or when you add the release 3.3 (?)
